// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiFinalTitoMatias.Data;

namespace WebApiFinalTitoMatias.Migrations
{
    [DbContext(typeof(DbHospitalContext))]
    partial class DbHospitalContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApiFinalTitoMatias.Models.Doctor", b =>
                {
                    b.Property<int>("Doctor_No")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Especialidad")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("HospitalCod")
                        .HasColumnType("int");

                    b.HasKey("Doctor_No")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.HasIndex("HospitalCod");

                    b.ToTable("Doctores");
                });

            modelBuilder.Entity("WebApiFinalTitoMatias.Models.Hospital", b =>
                {
                    b.Property<int>("Hospital_Cod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Num_Cama")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Hospital_Cod")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.ToTable("Hospitales");
                });

            modelBuilder.Entity("WebApiFinalTitoMatias.Models.Doctor", b =>
                {
                    b.HasOne("WebApiFinalTitoMatias.Models.Hospital", "Hospital")
                        .WithMany("Doctors")
                        .HasForeignKey("HospitalCod")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
